// src/components/react/views/GraphDataController.tsx
import { useSigma } from "@react-sigma/core";
import { type FC, type PropsWithChildren, useEffect } from "react";

import type { FiltersState } from "../types";

const GraphDataController: FC<PropsWithChildren<{ filters: FiltersState }>> = ({ filters, children }) => {
  const sigma = useSigma();
  const graph = sigma.getGraph();

  /**
   * Apply filters to graphology:
   */
  useEffect(() => {
    const { clusters, tags } = filters;
    graph.forEachNode((node, { cluster, tag }) =>
      graph.setNodeAttribute(node, "hidden", !clusters[cluster] || !tags[tag]),
    );
  }, [graph, filters]);

  return <>{children}</>;
};

export default GraphDataController;

// src/components/svelte/views/GraphDataController.svelte
<script lang="ts">
  import type { Sigma } from "sigma";
  import { type Snippet } from "svelte";
  import type { FiltersState } from "../types";

  let {
    sigma,
    filters,
    children,
  }: {
    sigma: Sigma;
    filters: FiltersState;
    children?: Snippet;
  } = $props();

  const graph = $derived(sigma.getGraph());

  $effect(() => {
    const { clusters, tags } = filters;
    graph.forEachNode((node, { cluster, tag }) =>
      graph.setNodeAttribute(node, "hidden", !clusters[cluster] || !tags[tag])
    );
  });
</script>

{@render children?.()}
