// src/components/svelte/views/GraphEventsController.svelte
<script lang="ts">
  import type { Sigma } from "sigma";
  import { onMount, type Snippet } from "svelte";

  function getMouseLayer() {
    return document.querySelector(".sigma-mouse");
  }

  let {
    sigma,
    setHoveredNode,
    children,
  }: {
    sigma: Sigma;
    setHoveredNode: (args: string | null) => void;
    children?: Snippet;
  } = $props();

  const graph = $derived(sigma.getGraph());

  onMount(() => {
    sigma.on("clickNode", ({ node }) => {
      if (!graph.getNodeAttribute(node, "hidden")) {
        window.open(graph.getNodeAttribute(node, "URL"), "_blank");
      }
    });

    sigma.on("enterNode", ({ node }) => {
      setHoveredNode(node);
      const mouseLayer = getMouseLayer();
      if (mouseLayer) mouseLayer.classList.add("mouse-pointer");
    });

    sigma.on("leaveNode", () => {
      setHoveredNode(null);
      const mouseLayer = getMouseLayer();
      if (mouseLayer) mouseLayer.classList.remove("mouse-pointer");
    });
  });
</script>

{@render children?.()}

// src/components/react/views/GraphEventsController.tsx
import { useRegisterEvents, useSigma } from "@react-sigma/core";
import { type FC, type PropsWithChildren, useEffect } from "react";

function getMouseLayer() {
  return document.querySelector(".sigma-mouse");
}

const GraphEventsController: FC<PropsWithChildren<{ setHoveredNode: (node: string | null) => void }>> = ({
  setHoveredNode,
  children,
}) => {
  const sigma = useSigma();
  const graph = sigma.getGraph();
  const registerEvents = useRegisterEvents();

  /**
   * Initialize here settings that require to know the graph and/or the sigma
   * instance:
   */
  useEffect(() => {
    registerEvents({
      clickNode({ node }) {
        if (!graph.getNodeAttribute(node, "hidden")) {
          window.open(graph.getNodeAttribute(node, "URL"), "_blank");
        }
      },
      enterNode({ node }) {
        setHoveredNode(node);
        // TODO: Find a better way to get the DOM mouse layer:
        const mouseLayer = getMouseLayer();
        if (mouseLayer) mouseLayer.classList.add("mouse-pointer");
      },
      leaveNode() {
        setHoveredNode(null);
        // TODO: Find a better way to get the DOM mouse layer:
        const mouseLayer = getMouseLayer();
        if (mouseLayer) mouseLayer.classList.remove("mouse-pointer");
      },
    });
  }, []);

  return <>{children}</>;
};

export default GraphEventsController;
