// src/components/svelte/views/Panel.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import ChevronUp from "../icons/ChevronUp.svelte";
  import ChevronDown from "../icons/ChevronDown.svelte";
  import AnimateHeight from "./AnimateHeight.svelte";

  const DURATION = 300;

  const {
    title,
    initiallyDeployed,
    children,
  }: {
    title: Snippet;
    initiallyDeployed?: boolean;
    children: Snippet;
  } = $props();

  let isDeployed = $state(initiallyDeployed || false);
  let dom = $state<HTMLDivElement | null>(null);

  $effect(() => {
    if (isDeployed)
      setTimeout(() => {
        if (dom)
          dom.parentElement?.scrollTo({
            top: dom.offsetTop - 5,
            behavior: "smooth",
          });
      }, DURATION);
  });
</script>

<div class="panel" bind:this={dom}>
  <h2>
    {@render title()}{" "}
    <button type="button" onclick={() => (isDeployed = !isDeployed)}>
      {#if isDeployed}
        <ChevronUp />
      {:else}
        <ChevronDown />
      {/if}
    </button>
  </h2>
  <AnimateHeight duration={DURATION} isOpen={isDeployed}>
    {#if isDeployed}
      {@render children()}
    {/if}
  </AnimateHeight>
</div>

// src/components/react/views/Panel.tsx
import { type FC, type PropsWithChildren, type ReactNode, useEffect, useRef, useState } from "react";
import AnimateHeight from "react-animate-height";
import { MdExpandLess, MdExpandMore } from "react-icons/md";

const DURATION = 300;

const Panel: FC<PropsWithChildren<{ title: ReactNode | string; initiallyDeployed?: boolean }>> = ({
  title,
  initiallyDeployed,
  children,
}) => {
  const [isDeployed, setIsDeployed] = useState(initiallyDeployed || false);
  const dom = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (isDeployed)
      setTimeout(() => {
        if (dom.current) dom.current.parentElement?.scrollTo({ top: dom.current.offsetTop - 5, behavior: "smooth" });
      }, DURATION);
  }, [isDeployed]);

  return (
    <div className="panel" ref={dom}>
      <h2>
        {title}{" "}
        <button type="button" onClick={() => setIsDeployed((v) => !v)}>
          {isDeployed ? <MdExpandLess /> : <MdExpandMore />}
        </button>
      </h2>
      <AnimateHeight duration={DURATION} height={isDeployed ? "auto" : 0}>
        {children}
      </AnimateHeight>
    </div>
  );
};

export default Panel;
