// src/components/svelte/views/Root.svelte
<script lang="ts">
  import { circlepack, circular, random } from "graphology-layout";
  import forceAtlas2 from "graphology-layout-forceatlas2";
  import FA2Layout from "graphology-layout-forceatlas2/worker";
  import { DirectedGraph } from "graphology";
  import type { Dataset, FiltersState } from "../types";
  import type { Settings } from "sigma/settings";
  import { createNodeImageProgram } from "@sigma/node-image";
  import { drawHover, drawLabel } from "../canvas-utils";
  import { constant, keyBy, mapValues, omit } from "../../common-utils";
  import { Sigma } from "sigma";
  import { onMount } from "svelte";
  import GraphSettingsController from "./GraphSettingsController.svelte";
  import GraphEventsController from "./GraphEventsController.svelte";
  import GraphDataController from "./GraphDataController.svelte";
  import { useDebounce } from "../use-debounce.svelte";
  import BookContent from "../icons/BookContent.svelte";
  import FullScreenControl from "./FullScreenControl.svelte";
  import ArrowsPointingIn from "../icons/ArrowsPointingIn.svelte";
  import ArrowsPointingOut from "../icons/ArrowsPointingOut.svelte";
  import ZoomControls from "./ZoomControls.svelte";
  import XMark from "../icons/XMark.svelte";
  import GraphTitle from "./GraphTitle.svelte";
  import SearchField from "./SearchField.svelte";
  import DescriptionPanel from "./DescriptionPanel.svelte";
  import ClustersPanel from "./ClustersPanel.svelte";
  import TagsPanel from "./TagsPanel.svelte";

  const graph = new DirectedGraph();
  const sigmaSettings: Partial<Settings> = {
    nodeProgramClasses: {
      image: createNodeImageProgram({
        size: { mode: "force", value: 256 },
      }),
    },
    defaultDrawNodeLabel: drawLabel,
    defaultDrawNodeHover: drawHover,
    defaultNodeType: "image",
    defaultEdgeType: "arrow",
    labelDensity: 0.07,
    labelGridCellSize: 60,
    labelRenderedSizeThreshold: 15,
    labelFont: "Lato, sans-serif",
    zIndex: true,
    // 下記を設定しないとエラーになる。 TODO: 記事にしたい
    // 参考: https://stackoverflow.com/questions/73144438/how-do-i-set-allowinvalidcontainer-in-sigmajs
    allowInvalidContainer: true,
  };

  let sigma = $state<Sigma | null>(null);
  let showContents = $state(false);
  let dataReady = $state(false);
  let dataset: Dataset | null = $state(null);
  let filtersState: FiltersState = $state({
    clusters: {},
    tags: {},
  });
  const debouncedHoveredNode = useDebounce<null | string>(null, 40);

  const setHoveredNode = (node: string | null) => {
    debouncedHoveredNode.update(node);
  };

  $inspect("dataset", dataset);

  fetch(`./dataset-sigma-demo.json`)
    .then((res) => res.json())
    .then((_dataset: Dataset) => {
      const clusters = keyBy(_dataset.clusters, "key");
      const tags = keyBy(_dataset.tags, "key");

      _dataset.nodes.forEach((node) =>
        graph.addNode(node.key, {
          ...node,
          ...omit(clusters[node.cluster], "key"),
          image: `./images/${tags[node.tag].image}`,
        })
      );

      random.assign(graph);
      // circular.assign(graph);

      // const settings = forceAtlas2.inferSettings(graph);
      // forceAtlas2.assign(graph, { settings, iterations: 1000 });

      _dataset.edges.forEach(([source, target]) =>
        graph.addEdge(source, target, { size: 1 })
      );

      // Use degrees as node sizes:
      const scores = graph
        .nodes()
        .map((node) => graph.getNodeAttribute(node, "score"));
      const minDegree = Math.min(...scores);
      const maxDegree = Math.max(...scores);
      const MIN_NODE_SIZE = 3;
      const MAX_NODE_SIZE = 30;
      graph.forEachNode((node) =>
        graph.setNodeAttribute(
          node,
          "size",
          ((graph.getNodeAttribute(node, "score") - minDegree) /
            (maxDegree - minDegree)) *
            (MAX_NODE_SIZE - MIN_NODE_SIZE) +
            MIN_NODE_SIZE
        )
      );

      filtersState = {
        clusters: mapValues(keyBy(_dataset.clusters, "key"), constant(true)),
        tags: mapValues(keyBy(_dataset.tags, "key"), constant(true)),
      };
      dataset = _dataset;
      requestAnimationFrame(() => (dataReady = true));
    });

  onMount(() => {
    const container = document.getElementById("sigma-container") as HTMLElement;
    sigma = new Sigma(graph, container, sigmaSettings);
  });

  $effect(() => {
    if (!dataReady || !sigma) return;
    const settings = forceAtlas2.inferSettings(graph);
    const fa2Layout = new FA2Layout(graph, {
      settings,
    });
    fa2Layout.start();

    setTimeout(() => {
      fa2Layout.stop();
    }, 30000);

    return () => {
      fa2Layout.stop();
      fa2Layout.kill();
    };
  });
</script>

<div id="app-root" class={showContents ? "show-contents" : ""}>
  <div class="react-sigma">
    <div class="sigma-container" id="sigma-container"></div>
    {#if sigma}
      <GraphSettingsController
        {sigma}
        debouncedHoveredNode={debouncedHoveredNode.value}
      />
      <GraphEventsController {sigma} {setHoveredNode} />
      <GraphDataController {sigma} filters={filtersState} />

      {#if dataReady && dataset}
        <div class="controls">
          <div class="react-sigma-control ico">
            <button
              type="button"
              class="show-contents"
              onclick={() => (showContents = true)}
              title="Show caption and description"
              aria-label="Show caption and description"
            >
              <BookContent />
            </button>
          </div>
          <div class="react-sigma-control ico">
            <FullScreenControl>
              {#snippet exitFullScreenLabel()}
                <ArrowsPointingIn />
              {/snippet}
              {#snippet enterFullScreenLabel()}
                <ArrowsPointingOut />
              {/snippet}
            </FullScreenControl>
          </div>
          <ZoomControls {sigma} />
        </div>
        <div class="contents">
          <div class="ico">
            <button
              type="button"
              class="ico hide-contents"
              onclick={() => (showContents = false)}
              title="Show caption and description"
            >
              <XMark />
            </button>
          </div>
          <GraphTitle {sigma} filters={filtersState} />
          <div class="panels">
            <SearchField {sigma} filters={filtersState} />
            <DescriptionPanel />
            <ClustersPanel
              {sigma}
              clusters={dataset.clusters}
              filters={filtersState}
              setClusters={(clusters) =>
                (filtersState = {
                  ...filtersState,
                  clusters,
                })}
              toggleCluster={(cluster) => {
                filtersState = {
                  ...filtersState,
                  clusters: filtersState.clusters[cluster]
                    ? omit(filtersState.clusters, cluster)
                    : { ...filtersState.clusters, [cluster]: true },
                };
              }}
            />
            <TagsPanel
              {sigma}
              tags={dataset.tags}
              filters={filtersState}
              setTags={(tags) =>
                (filtersState = {
                  ...filtersState,
                  tags,
                })}
              toggleTag={(tag) => {
                filtersState = {
                  ...filtersState,
                  tags: filtersState.tags[tag]
                    ? omit(filtersState.tags, tag)
                    : { ...filtersState.tags, [tag]: true },
                };
              }}
            />
          </div>
        </div>
      {/if}
    {/if}
  </div>
</div>

// src/components/react/views/Root.tsx
import { FullScreenControl, SigmaContainer, ZoomControl } from "@react-sigma/core";
import { createNodeImageProgram } from "@sigma/node-image";
import { DirectedGraph } from "graphology";
import { constant, keyBy, mapValues, omit } from "lodash";
import { type FC, useEffect, useMemo, useState } from "react";
import { BiBookContent, BiRadioCircleMarked } from "react-icons/bi";
import { BsArrowsFullscreen, BsFullscreenExit, BsZoomIn, BsZoomOut } from "react-icons/bs";
import { GrClose } from "react-icons/gr";
import type { Settings } from "sigma/settings";

import { drawHover, drawLabel } from "../canvas-utils";
import ClustersPanel from "./ClustersPanel";
import DescriptionPanel from "./DescriptionPanel";
import GraphDataController from "./GraphDataController";
import GraphEventsController from "./GraphEventsController";
import GraphSettingsController from "./GraphSettingsController";
import GraphTitle from "./GraphTitle";
import SearchField from "./SearchField";
import TagsPanel from "./TagsPanel";
import type { Dataset, FiltersState } from "../types";

const Root: FC = () => {
  const graph = useMemo(() => new DirectedGraph(), []);
  const [showContents, setShowContents] = useState(false);
  const [dataReady, setDataReady] = useState(false);
  const [dataset, setDataset] = useState<Dataset | null>(null);
  const [filtersState, setFiltersState] = useState<FiltersState>({
    clusters: {},
    tags: {},
  });
  const [hoveredNode, setHoveredNode] = useState<string | null>(null);
  const sigmaSettings: Partial<Settings> = useMemo(
    () => ({
      nodeProgramClasses: {
        image: createNodeImageProgram({
          size: { mode: "force", value: 256 },
        }),
      },
      defaultDrawNodeLabel: drawLabel,
      defaultDrawNodeHover: drawHover,
      defaultNodeType: "image",
      defaultEdgeType: "arrow",
      labelDensity: 0.07,
      labelGridCellSize: 60,
      labelRenderedSizeThreshold: 15,
      labelFont: "Lato, sans-serif",
      zIndex: true,
      // 下記を設定しないとエラーになる。 TODO: 記事にしたい
      // 参考: https://stackoverflow.com/questions/73144438/how-do-i-set-allowinvalidcontainer-in-sigmajs
      allowInvalidContainer: true,
    }),
    [],
  );

  // Load data on mount:
  useEffect(() => {
    fetch(`./dataset-sigma-demo.json`)
      .then((res) => res.json())
      .then((dataset: Dataset) => {
        const clusters = keyBy(dataset.clusters, "key");
        const tags = keyBy(dataset.tags, "key");

        dataset.nodes.forEach((node) =>
          graph.addNode(node.key, {
            ...node,
            ...omit(clusters[node.cluster], "key"),
            image: `./images/${tags[node.tag].image}`,
          }),
        );
        dataset.edges.forEach(([source, target]) => graph.addEdge(source, target, { size: 1 }));

        // Use degrees as node sizes:
        const scores = graph.nodes().map((node) => graph.getNodeAttribute(node, "score"));
        const minDegree = Math.min(...scores);
        const maxDegree = Math.max(...scores);
        const MIN_NODE_SIZE = 3;
        const MAX_NODE_SIZE = 30;
        graph.forEachNode((node) =>
          graph.setNodeAttribute(
            node,
            "size",
            ((graph.getNodeAttribute(node, "score") - minDegree) / (maxDegree - minDegree)) *
              (MAX_NODE_SIZE - MIN_NODE_SIZE) +
              MIN_NODE_SIZE,
          ),
        );

        setFiltersState({
          clusters: mapValues(keyBy(dataset.clusters, "key"), constant(true)),
          tags: mapValues(keyBy(dataset.tags, "key"), constant(true)),
        });
        setDataset(dataset);
        requestAnimationFrame(() => setDataReady(true));
      });
  }, []);

  if (!dataset) return null;

  return (
    <div id="app-root" className={showContents ? "show-contents" : ""}>
      <SigmaContainer graph={graph} settings={sigmaSettings} className="react-sigma">
        <GraphSettingsController hoveredNode={hoveredNode} />
        <GraphEventsController setHoveredNode={setHoveredNode} />
        <GraphDataController filters={filtersState} />

        {dataReady && (
          <>
            <div className="controls">
              <div className="react-sigma-control ico">
                <button
                  type="button"
                  className="show-contents"
                  onClick={() => setShowContents(true)}
                  title="Show caption and description"
                >
                  <BiBookContent />
                </button>
              </div>
              <FullScreenControl className="ico">
                <BsArrowsFullscreen />
                <BsFullscreenExit />
              </FullScreenControl>

              <ZoomControl className="ico">
                <BsZoomIn />
                <BsZoomOut />
                <BiRadioCircleMarked />
              </ZoomControl>
            </div>
            <div className="contents">
              <div className="ico">
                <button
                  type="button"
                  className="ico hide-contents"
                  onClick={() => setShowContents(false)}
                  title="Show caption and description"
                >
                  <GrClose />
                </button>
              </div>
              <GraphTitle filters={filtersState} />
              <div className="panels">
                <SearchField filters={filtersState} />
                <DescriptionPanel />
                <ClustersPanel
                  clusters={dataset.clusters}
                  filters={filtersState}
                  setClusters={(clusters) =>
                    setFiltersState((filters) => ({
                      ...filters,
                      clusters,
                    }))
                  }
                  toggleCluster={(cluster) => {
                    setFiltersState((filters) => ({
                      ...filters,
                      clusters: filters.clusters[cluster]
                        ? omit(filters.clusters, cluster)
                        : { ...filters.clusters, [cluster]: true },
                    }));
                  }}
                />
                <TagsPanel
                  tags={dataset.tags}
                  filters={filtersState}
                  setTags={(tags) =>
                    setFiltersState((filters) => ({
                      ...filters,
                      tags,
                    }))
                  }
                  toggleTag={(tag) => {
                    setFiltersState((filters) => ({
                      ...filters,
                      tags: filters.tags[tag] ? omit(filters.tags, tag) : { ...filters.tags, [tag]: true },
                    }));
                  }}
                />
              </div>
            </div>
          </>
        )}
      </SigmaContainer>
    </div>
  );
};

export default Root;
