// src/components/svelte/views/TagsPanel.svelte
<script lang="ts">
  import type { Sigma } from "sigma";
  import type { FiltersState, Tag } from "../types";
  import { keyBy, mapValues, sortBy, values } from "../../common-utils";
  import TagOutline from "../icons/TagOutline.svelte";
  import Panel from "./Panel.svelte";
  import CheckCircle from "../icons/CheckCircle.svelte";
  import XCircle from "../icons/XCircle.svelte";

  const {
    sigma,
    tags,
    filters,
    toggleTag,
    setTags,
  }: {
    sigma: Sigma;
    tags: Tag[];
    filters: FiltersState;
    toggleTag: (tag: string) => void;
    setTags: (tags: Record<string, boolean>) => void;
  } = $props();

  const graph = sigma.getGraph();

  let nodesPerTag = $derived.by(() => {
    const index: Record<string, number> = {};
    graph.forEachNode((_, { tag }) => (index[tag] = (index[tag] || 0) + 1));
    return index;
  });
  let maxNodesPerTag = $derived(Math.max(...values(nodesPerTag)));
  let visibleTagsCount = $derived(Object.keys(filters.tags).length);

  // svelte-ignore state_referenced_locally
  let visibleNodesPerTag = $state(nodesPerTag);

  $effect(() => {
    filters;

    requestAnimationFrame(() => {
      const index: Record<string, number> = {};
      graph.forEachNode(
        (_, { tag, hidden }) => !hidden && (index[tag] = (index[tag] || 0) + 1)
      );
      visibleNodesPerTag = index;
    });
  });

  const sortedTags = $derived(
    sortBy(tags, (tag) =>
      tag.key === "unknown" ? Infinity : -nodesPerTag[tag.key]
    )
  );
</script>

{#snippet title()}
  <TagOutline class="text-muted" /> Categories
  {#if visibleTagsCount < tags.length}
    <span class="text-muted text-small">
      {" "}
      ({visibleTagsCount} / {tags.length})
    </span>
  {/if}
{/snippet}

<Panel {title} initiallyDeployed={false}>
  <p>
    <i class="text-muted"
      >Click a category to show/hide related pages from the network.</i
    >
  </p>
  <p class="buttons">
    <button
      class="btn"
      onclick={() => setTags(mapValues(keyBy(tags, "key"), () => true))}
    >
      <CheckCircle /> Check all
    </button>{" "}
    <button class="btn" onclick={() => setTags({})}>
      <XCircle /> Uncheck all
    </button>
  </p>
  <ul>
    {#each sortedTags as tag (tag.key)}
      {@const nodesCount = nodesPerTag[tag.key]}
      {@const visibleNodesCount = visibleNodesPerTag[tag.key] || 0}
      <li
        class="caption-row"
        title={`${nodesCount} page${nodesCount > 1 ? "s" : ""}${
          visibleNodesCount !== nodesCount
            ? visibleNodesCount > 0
              ? ` (only ${visibleNodesCount > 1 ? `${visibleNodesCount} are` : "one is"} visible)`
              : " (all hidden)"
            : ""
        }`}
      >
        <input
          type="checkbox"
          checked={filters.tags[tag.key] || false}
          onchange={() => toggleTag(tag.key)}
          id={`tag-${tag.key}`}
        />
        <label for={`tag-${tag.key}`}>
          <span
            class="circle"
            style={`background-image: url(./images/${tag.image})`}
          ></span>{" "}
          <div class="node-label">
            <span>{tag.key}</span>
            <div
              class="bar"
              style={`width: ${(100 * nodesCount) / maxNodesPerTag + "%"}`}
            >
              <div
                class="inside-bar"
                style={`width: ${(100 * visibleNodesCount) / nodesCount + "%"}`}
              ></div>
            </div>
          </div>
        </label>
      </li>
    {/each}
  </ul>
</Panel>

// src/components/react/views/TagsPanel.tsx
import { useSigma } from "@react-sigma/core";
import { keyBy, mapValues, sortBy, values } from "lodash";
import { type FC, useEffect, useMemo, useState } from "react";
import { AiOutlineCheckCircle, AiOutlineCloseCircle } from "react-icons/ai";
import { MdCategory } from "react-icons/md";

import Panel from "./Panel";
import type { FiltersState, Tag } from "../types";

const TagsPanel: FC<{
  tags: Tag[];
  filters: FiltersState;
  toggleTag: (tag: string) => void;
  setTags: (tags: Record<string, boolean>) => void;
}> = ({ tags, filters, toggleTag, setTags }) => {
  const sigma = useSigma();
  const graph = sigma.getGraph();

  const nodesPerTag = useMemo(() => {
    const index: Record<string, number> = {};
    graph.forEachNode((_, { tag }) => (index[tag] = (index[tag] || 0) + 1));
    return index;
  }, []);

  const maxNodesPerTag = useMemo(() => Math.max(...values(nodesPerTag)), [nodesPerTag]);
  const visibleTagsCount = useMemo(() => Object.keys(filters.tags).length, [filters]);

  const [visibleNodesPerTag, setVisibleNodesPerTag] = useState<Record<string, number>>(nodesPerTag);
  useEffect(() => {
    // To ensure the graphology instance has up to date "hidden" values for
    // nodes, we wait for next frame before reindexing. This won't matter in the
    // UX, because of the visible nodes bar width transition.
    requestAnimationFrame(() => {
      const index: Record<string, number> = {};
      graph.forEachNode((_, { tag, hidden }) => !hidden && (index[tag] = (index[tag] || 0) + 1));
      setVisibleNodesPerTag(index);
    });
  }, [filters]);

  const sortedTags = useMemo(
    () => sortBy(tags, (tag) => (tag.key === "unknown" ? Infinity : -nodesPerTag[tag.key])),
    [tags, nodesPerTag],
  );

  return (
    <Panel
      title={
        <>
          <MdCategory className="text-muted" /> Categories
          {visibleTagsCount < tags.length ? (
            <span className="text-muted text-small">
              {" "}
              ({visibleTagsCount} / {tags.length})
            </span>
          ) : (
            ""
          )}
        </>
      }
    >
      <p>
        <i className="text-muted">Click a category to show/hide related pages from the network.</i>
      </p>
      <p className="buttons">
        <button className="btn" onClick={() => setTags(mapValues(keyBy(tags, "key"), () => true))}>
          <AiOutlineCheckCircle /> Check all
        </button>{" "}
        <button className="btn" onClick={() => setTags({})}>
          <AiOutlineCloseCircle /> Uncheck all
        </button>
      </p>
      <ul>
        {sortedTags.map((tag) => {
          const nodesCount = nodesPerTag[tag.key];
          const visibleNodesCount = visibleNodesPerTag[tag.key] || 0;
          return (
            <li
              className="caption-row"
              key={tag.key}
              title={`${nodesCount} page${nodesCount > 1 ? "s" : ""}${
                visibleNodesCount !== nodesCount
                  ? visibleNodesCount > 0
                    ? ` (only ${visibleNodesCount > 1 ? `${visibleNodesCount} are` : "one is"} visible)`
                    : " (all hidden)"
                  : ""
              }`}
            >
              <input
                type="checkbox"
                checked={filters.tags[tag.key] || false}
                onChange={() => toggleTag(tag.key)}
                id={`tag-${tag.key}`}
              />
              <label htmlFor={`tag-${tag.key}`}>
                <span className="circle" style={{ backgroundImage: `url(./images/${tag.image})` }} />{" "}
                <div className="node-label">
                  <span>{tag.key}</span>
                  <div className="bar" style={{ width: (100 * nodesCount) / maxNodesPerTag + "%" }}>
                    <div
                      className="inside-bar"
                      style={{
                        width: (100 * visibleNodesCount) / nodesCount + "%",
                      }}
                    />
                  </div>
                </div>
              </label>
            </li>
          );
        })}
      </ul>
    </Panel>
  );
};

export default TagsPanel;
